name: Deploy Discord Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'  # Uruchamia co 5 minut

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Ustawienie wersji Pythona na 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install discord.py Pillow requests

      - name: Run bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: python botdcpjoto.py
