name: Deploy Discord Bot

#on:
#  push:
#    branches:
#     - master
#  schedule:
#    - cron: '0 * * * *'  # Uruchamia co godzinę na początku godziny

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master  # Zmienia gałąź na master podczas pobierania kodu

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Ustawienie wersji Pythona na 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install discord.py Pillow requests

      - name: Run bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          timeout 3600 python -u botdcpjoto.py  # Uruchamia bota na maksymalnie 3600 sekund (1 godzina)
