name: Deploy Discord Bot

on:
  push:
    branches:
      - master  # Ustaw na nazwę gałęzi, którą używasz

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Możesz ustawić wersję Pythona, której potrzebujesz

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install discord.py Pillow requests

      - name: Run bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}  # Używa tokenu jako zmiennej środowiskowej
        run: python botdcpjoto.py
